### ISSUE TITLE
Would it be useful to access the reMarkable remotely with rMAPI?

### ISSUE THREAD

**Issue by juruen** [reHackable/maxio#15]
Hi!

I spent some time working on [rMAPI](https://github.com/juruen/rmapi), a Go app to access the reMarkable remotely using the cloud API. It allows you to copy files and directories from/to it without plugining the device.

I see `maxio` uses `ssh/scp` to connect to the device. Would it be useful to create a PR to add the option of using `rMAPI` to access the device remotely? 

Thank you!

**Comment by edupont** [comment]
Hi @juruen,

I have not played with rMAPI so far, since I don't use the cloud services on the tablet. Is there a way to get and send the `.lines` files through that API? Or is it restricted to PDF / PNG files? In which form do the notebooks appear? Is there a way to retrieve the custom templates? Am I asking too many questions?

**Comment by dvandyk** [comment]
Hi @edupont,

I have cobbled together a small Python module and command line script to synchronize files from the
rM cloud [here](https://github.com/dvandyk/rmt). I plan to have a git-like set of commands, some of which
are already implemented:

    rmt init DIR CODE
    rmt fetch
    rmt checkout

The latter is supposed to checkout the most recent **annotated** PDF. However, the cloud API does only
provide the original, and the ```lines``` file. I would love to use your code in my project. Is it OK to use it in
an LGPL project?

**Comment by edupont** [comment]
Yes, please reuse and improve it as much as you want.



On May 26, 2018 9:27:55 PM UTC, Danny van Dyk <notifications@github.com> wrote:
>Hi @edupont,
>
>I have cobbled together a small Python module and command line script
>to synchronize files from the
>rM cloud [here](https://github.com/dvandyk/rmt). I plan to have a
>git-like set of commands, some of which
>are already implemented:
>
>    rmt init DIR CODE
>    rmt fetch
>    rmt checkout
>
>The latter is supposed to checkout the most recent **annotated** PDF.
>However, the cloud API does only
>provide the original, and the ```lines``` file. I would love to use
>your code in my project. Is it OK to use it in
>an LGPL project?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/reHackable/maxio/issues/15#issuecomment-392289166

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
