### ISSUE TITLE
Enhancement: "Highlighter" pen should be renderd yellow

### ISSUE THREAD

**Issue by justfortherec** [reHackable/maxio#2]
Hi,

I think this is a great script and I applaud your reverse engineering the format.

I am going to dump a couple of details that I found into your issues. They might turn out to be interesting for this project. If not, please ignore them and accept my apologies.

Stroke color of the highlighter pen is yellow when exporting drawings and annotated documents through the remarkable desktop app. This is also documented in the [getting started guide (p 3, PDF)](https://support.remarkable.com/hc/en-us/article_attachments/115010295569/Get_started_with_reading.pdf)

It might be a nice enhancement to also select a translucent yellow for highlighter strokes.

Cheers

**Comment by edupont** [comment]
Hi Franz,

Thanks for looking into this, and for trying it out.

You are perfectly right. The rM2svg currently makes no adaptation 
according to the tools used. Even the highlighter looks like a strike 
through the highlighted text.

The magic happens in lines 120 - 123. The `pen` argument is not used. 
Feel free to modify the `style=` attribute of the polyline. If the pen 
selected is 5 (Highlighter), select a wider stroke (feel free to 
experiment to see how wide it has to be) and a partially-transparent 
(`stroke-opacity:0.5`, select best fitting value) yellow 
(`stroke_colour[colour] if pen != 5 else "yellow"`).

Try to cross 2 highlighter strokes on the tablet, see if you get the 
correspondingly darker shade of yellow in the generated SVG.

Note that some users would prefer the Highlighter to stay grey in the 
exported images.

Feel free to send patches and ideas, and to experiment around.

Best regards,
Émeric

**Comment by florian-wagner** [comment]
Hi @justfortherec,

if you update and use the `-c` option, i.e. `exportNotebook YOURFILENAME -c`, the marker will be yellow. Hope that helps. See #7 for more info.

**Comment by edupont** [comment]
Thanks for tackling those issues!

**Comment by DavidValin** [comment]
I really need to export the sketches in PDF with grey highlight color. This is not happening when exported through the web UI. It's really annoying to find my documents changing the look and feel of what I just liked as it was drawed.

**Comment by edupont** [comment]
@DavidValin Thanks for chipping in. I was annoyed by the yellow color of the exported Highlight, especially the shade of yellow that was selected. The rM2svg script exports the highlights as grey by default.
